### ISSUE TITLE
Get Iteration 0 Segmentation fault: 11 after running ./mpc

### ISSUE THREAD

**Issue by HarrisonHYZ** [udacity/CarND-MPC-Quizzes#20]
After "cmake .. && make " command, I run mpc with "./mpc". However, I always get the "Iteration 0
Segmentation fault: 11" error.
After testing which line has the error with "cout" command, I found the codes below cause this error.

CppAD::ipopt::solve<Dvector, FG_eval>(
      options, vars, vars_lowerbound, vars_upperbound, constraints_lowerbound,
      constraints_upperbound, fg_eval, solution);

Did anyone have the same error before?

Actually, even with the solution file, I still have the same error. So I'm thinking maybe I didn't install ipopt properly. Please give me some help. I'm really stuck.

**Comment by mvirgo** [comment]
Hi there - 

Please note that Knowledge and Student Hub should be utilized for these type of issues.

Most of the time, a Segmentation Fault on this project occurs due to an index out of bounds error. I'd check for those first.

If you think it is likely due to your ipopt installation, note that there is also now a classroom workspace in the MPC Project lesson with ipopt pre-installed - if you want, you can add your code in as a new directory there, and test out if the error still exists.

**Comment by HarrisonHYZ** [comment]
@mvirgo Hi, I tried the same codes in the classroom workspace, it works well and I got the correct result. Now I'm doing the mpc project, still get the same segmentation fault: 11 with the first iteration at the same code line. And I copy my code to the classroom workspace. It compiles successfully and can run the ./mpc. Please suggest the next step to debug this. Thank you.

**Comment by mvirgo** [comment]
As I noted before, you need to try asking Knowledge and Student Hub. This is not the place for debugging your own code, but for issues related to the code contained in the repository.

The most common reason for this is on an index out of bounds error, or if you have a pointer going awry, although the pointer issue is usually less common on this project. So, any arrays you set, or loops you do, I would check to make sure you aren't trying to call something outside of the bounds of the given array.

**Comment by mvirgo** [comment]
Closing since no further comments in 2+ weeks
